{"uuid": "ed52a18f-02bd-45cd-a490-3ae6ea69354e", "children": ["20fe5d8f-d1d9-4088-b4fc-ed0c52b51eb1", "aaddde85-b28a-4f20-a020-34eef880bbbc"], "befores": [{"name": "_Class__pytest_setup_class", "status": "passed", "start": 1596044281841, "stop": 1596044281841}], "afters": [{"name": "_Class__pytest_setup_class::0", "status": "broken", "statusDetails": {"message": "AttributeError: type object 'TestCase' has no attribute 'driver'\n", "trace": "  File \"D:\\python\\lib\\site-packages\\allure_commons\\_allure.py\", line 185, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"D:\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 800, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\python\\lib\\site-packages\\_pytest\\python.py\", line 705, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"D:\\python\\lib\\site-packages\\_pytest\\python.py\", line 632, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\appium_PO_kaoyan\\test_case\\test_cases.py\", line 23, in teardown_class\n    Common(self.driver).send_email('../report/pytest_report.html')\n"}, "start": 1596044314264, "stop": 1596044314265}], "start": 1596044281841, "stop": 1596044314265}